### ISSUE TITLE
참고: 스터디원 분들 중 github 웹 페이지 사용 여부 확인

### ISSUE THREAD

**Issue by ianychoi** [openstack-kr/study-engineering#11]
여기에 댓글 남겨주시면 됩니다.

**Comment by tolty** [comment]
(강효성)
사이트에만 가입했지 실제 사용은 처음입니다.^^;;

**Comment by cyber43** [comment]
github 잘 모르지만 가입해놓고,  watch와 Fork정도만 이해하고 있습니다. 
(정종준)
